apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: '{{.Release.Name}}-{{.Values.component.name}}'
  name: '{{.Release.Name}}-party-interaction-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: '{{.Release.Name}}-party-interaction-management-api'
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-{{.Values.component.name}}'
        impl: '{{.Release.Name}}-party-interaction-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: '{{.Release.Name}}-mongodb'
        - name: RELEASE_NAME
          value: '{{.Release.Name}}'
        - name: COMPONENT_NAME
          value: '{{.Release.Name}}-{{.Values.component.name}}'
        image: '{{.Values.images.tmf683}}'
        imagePullPolicy: Always
        name: '{{.Release.Name}}-party-interaction-management-api'
        ports:
        - containerPort: 8080
          name: '{{.Release.Name}}-party-i'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyInteraction/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
